# Generated by Django 6.0.7 on 2026-08-19 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shipmentstatuslog',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='assigned_driver',
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentstatuslog',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='logistics.shipment'),
        ),
    ]
